version: "3.2"

services:
  hydra:
    image: oryd/hydra:v0.10.10
    ports:
      - 9000:4444
    environment:
      - SYSTEM_SECRET=this-is-the-system-secret
      - DATABASE_URL=postgres://hydra:secret@db:5432/hydra?sslmode=disable
      - ISSUER=https://localhost:9000/
      - CONSENT_URL=http://localhost:9020/consent
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST
      - CORS_ALLOWED_HEADERS=Authorization
    networks:
      - hydra
    links:
      - db
  consent-app:
    image: oryd/hydra-consent-app-express:latest
    ports:
      - 9020:3000
    environment:
      - HYDRA_CLIENT_ID=consent-app
      - HYDRA_CLIENT_SECRET=consent-secret
      - HYDRA_URL=https://hydra:4444
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - hydra
    links:
      - hydra
  consumer-app:
    image: nginx:latest
    ports:
      - 9030:80
    volumes:
      - "./consumer-app/:/usr/share/nginx/html:ro"
    links:
      - hydra
      - consent-app
    networks:
      - hydra
  api-server:
    build:
      context: ./api-server/
    ports:
      - 9040:5000
    volumes:
      - "./api-server/:/usr/src/app:ro"
    links:
      - hydra
    networks:
      - hydra
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - hydra

networks:
  hydra:
